# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdemg < Formula
  desc "Multi-Dimensional Emergent Memory Graph — cognitive substrate for AI agents"
  homepage "https://github.com/reh3376/mdemg"
  version "0.11.0-beta.1"

  depends_on "docker" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/reh3376/mdemg/releases/download/v0.11.0-beta.1/mdemg_0.11.0-beta.1_darwin_amd64.tar.gz"
      sha256 "13957a0b8d742a2ffc71017df6d97b156737c3eb2cbb3ddb04afaeff71305187"

      define_method(:install) do
        bin.install "mdemg"
        man1.install Dir["man/man1/*.1"]
        # UxTS plugin (default-enabled REASONING module)
        plugdir = share/"mdemg/plugins/uxts-module"
        plugdir.install "uxts-module"
        plugdir.install "plugins/uxts-module/manifest.json"
        # Obsidian plugin (INGESTION module for Obsidian vault parsing)
        obsdir = share/"mdemg/plugins/obsidian-module"
        obsdir.install "obsidian-module"
        obsdir.install "plugins/obsidian-module/manifest.json"
        # Docker Compose file (embedded in binary, also available for inspection)
        share.install "docker-compose.yml" => "mdemg/docker-compose.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/reh3376/mdemg/releases/download/v0.11.0-beta.1/mdemg_0.11.0-beta.1_darwin_arm64.tar.gz"
      sha256 "2d6f501452bbd9dfea8dc644bf9bcb06d7506248d851b6df12095cc54d924531"

      define_method(:install) do
        bin.install "mdemg"
        man1.install Dir["man/man1/*.1"]
        # UxTS plugin (default-enabled REASONING module)
        plugdir = share/"mdemg/plugins/uxts-module"
        plugdir.install "uxts-module"
        plugdir.install "plugins/uxts-module/manifest.json"
        # Obsidian plugin (INGESTION module for Obsidian vault parsing)
        obsdir = share/"mdemg/plugins/obsidian-module"
        obsdir.install "obsidian-module"
        obsdir.install "plugins/obsidian-module/manifest.json"
        # Docker Compose file (embedded in binary, also available for inspection)
        share.install "docker-compose.yml" => "mdemg/docker-compose.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/reh3376/mdemg/releases/download/v0.11.0-beta.1/mdemg_0.11.0-beta.1_linux_amd64.tar.gz"
      sha256 "a0553eae03d646dc3f156c7bb6dd50c9ef5ab9d4894a99c2e6d5c9286a7259d5"
      define_method(:install) do
        bin.install "mdemg"
        man1.install Dir["man/man1/*.1"]
        # UxTS plugin (default-enabled REASONING module)
        plugdir = share/"mdemg/plugins/uxts-module"
        plugdir.install "uxts-module"
        plugdir.install "plugins/uxts-module/manifest.json"
        # Obsidian plugin (INGESTION module for Obsidian vault parsing)
        obsdir = share/"mdemg/plugins/obsidian-module"
        obsdir.install "obsidian-module"
        obsdir.install "plugins/obsidian-module/manifest.json"
        # Docker Compose file (embedded in binary, also available for inspection)
        share.install "docker-compose.yml" => "mdemg/docker-compose.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/reh3376/mdemg/releases/download/v0.11.0-beta.1/mdemg_0.11.0-beta.1_linux_arm64.tar.gz"
      sha256 "7242aa98fab41b1c3ffc85718b728d2f346ca3cd0c8932ede0a83897b14c40c3"
      define_method(:install) do
        bin.install "mdemg"
        man1.install Dir["man/man1/*.1"]
        # UxTS plugin (default-enabled REASONING module)
        plugdir = share/"mdemg/plugins/uxts-module"
        plugdir.install "uxts-module"
        plugdir.install "plugins/uxts-module/manifest.json"
        # Obsidian plugin (INGESTION module for Obsidian vault parsing)
        obsdir = share/"mdemg/plugins/obsidian-module"
        obsdir.install "obsidian-module"
        obsdir.install "plugins/obsidian-module/manifest.json"
        # Docker Compose file (embedded in binary, also available for inspection)
        share.install "docker-compose.yml" => "mdemg/docker-compose.yml"
      end
    end
  end

  def post_install
    # Runs on both install and upgrade. On fresh install, no Docker instances
    # exist, so upgradeDockerInstances returns silently (< 200ms overhead).
    system bin/"mdemg", "upgrade", "--docker-only"
  end

  def caveats
    <<~EOS
      Docker is required for running MDEMG services.
      After 'brew upgrade mdemg', running Docker instances are updated automatically.
      Jiminy inner-voice guidance is configured during 'mdemg init'.

      Local LLM (mdemg-llm-v1, Phase 13.5 production canonical):
        brew install ollama          # one-time distribution prereq
        mdemg model pull             # RAM-auto picks Q4/Q5/Q8 quant
        # → prints MDEMG_MODEL_PATH for your .env

      OpenAI fallback if you don't want a local LLM:
        Default models: gpt-5.4-mini (OpenAI) or qwen3:8b (Ollama).

      Run 'mdemg init' in your project directory to get started.
    EOS
  end

  test do
    system "#{bin}/mdemg", "version"
  end
end
