# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mdemg < Formula
  desc "Multi-Dimensional Emergent Memory Graph — cognitive substrate for AI agents"
  homepage "https://github.com/reh3376/mdemg"
  version "0.2.14"

  depends_on "docker" => :optional
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/reh3376/mdemg/releases/download/v0.2.14/mdemg_0.2.14_darwin_amd64.tar.gz"
    sha256 "40bafcd9c20ac9ca43f3f72fe00b53e15069feca20d3096ce853ecab6315086e"

    define_method(:install) do
      bin.install "mdemg"
      man1.install Dir["man/man1/*.1"]
      # UxTS plugin (default-enabled REASONING module)
      plugdir = share/"mdemg/plugins/uxts-module"
      plugdir.install "uxts-module"
      plugdir.install "plugins/uxts-module/manifest.json"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/reh3376/mdemg/releases/download/v0.2.14/mdemg_0.2.14_darwin_arm64.tar.gz"
    sha256 "ab821e191d467789164a4e5377969a4f1ad9125c2f1541bf1f2c08dadcd513cc"

    define_method(:install) do
      bin.install "mdemg"
      man1.install Dir["man/man1/*.1"]
      # UxTS plugin (default-enabled REASONING module)
      plugdir = share/"mdemg/plugins/uxts-module"
      plugdir.install "uxts-module"
      plugdir.install "plugins/uxts-module/manifest.json"
    end
  end

  test do
    system "#{bin}/mdemg", "version"
  end
end
