# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdemg" do
  name "mdemg"
  desc "Multi-Dimensional Emergent Memory Graph — cognitive substrate for AI agents"
  homepage "https://github.com/reh3376/mdemg"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdemg"
  depends_on formula: [
      "docker",
    ]

  on_macos do
    on_intel do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_darwin_amd64.tar.gz"
      sha256 "4ea4817c370300969d4bb0ccd07c0ee2128a3f4628d40f4cddd59aa709d98387"
    end
    on_arm do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_darwin_arm64.tar.gz"
      sha256 "c45d3ca1c837f299b862a39710ef9acb0d5ca4b15afe4c587bddc5cec61361dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_linux_amd64.tar.gz"
      sha256 "825b8017bccde6423108e08df6f9184f2b43a6c6259b1f561a60c4f72720d557"
    end
  end

  # No zap stanza required
end
