# This file was generated by GoReleaser. DO NOT EDIT.
cask "mdemg" do
  name "mdemg"
  desc "Multi-Dimensional Emergent Memory Graph — cognitive substrate for AI agents"
  homepage "https://github.com/reh3376/mdemg"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mdemg"
  depends_on formula: [
      "docker",
    ]

  on_macos do
    on_intel do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_darwin_amd64.tar.gz"
      sha256 "8067cfcc6760da132caddf86cd27012bb0b2ae1c3944f1e0a0e14606133e9aee"
    end
    on_arm do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_darwin_arm64.tar.gz"
      sha256 "2f5c4640715b077962a62c43875437132cbe6f0143ac380b9cf2f7cd6d5a39dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/reh3376/mdemg/releases/download/v#{version}/mdemg_#{version}_linux_amd64.tar.gz"
      sha256 "d95193752f2b69318979195ddb7d3c27269d4286851724583acba83e3c63ad79"
    end
  end

  # No zap stanza required
end
